#!/usr/bin/env python3
# GENERATED MIRROR of .claude/skills/orchestrator/scripts/flow-state.py — DO NOT EDIT THIS FILE.
# Edit the .claude source and regenerate:
#   python3 docs/orchestra/sync-agent-config.py

"""Read `references/flow.json` ONE BLOCK AT A TIME.

The graph is ~48 KB / 30 states. Inlining it into SKILL.md would spend the whole
compaction-survivable budget on routing data the session needs one state of, so
the skill body carries the laws and this script serves the graph on demand.

  flow-state.py <state>        one state's block, pretty-printed
  flow-state.py --list         the entry state and every state name
  flow-state.py --meta <key>   roles|levels|state_files|interrupts|invariants|
                               cloud|context_discipline|schema|title|version

Resolves the graph RELATIVE TO ITSELF, so it works from any cwd — repo root,
a worktree, anywhere. Exits 1 with what IS available on an unknown name.
"""
import json
import os
import sys

FLOW = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "references", "flow.json")
USAGE = "usage: flow-state.py <state> | --list | --meta <key>"


def die(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def main(argv):
    if not argv:
        die(USAGE)
    try:
        with open(FLOW) as f:
            graph = json.load(f)
    except Exception as exc:                     # missing or corrupt graph is fatal, never silent
        die(f"cannot read {os.path.normpath(FLOW)}: {exc}")

    states = graph.get("states", {})
    names = sorted(states)

    if argv[0] == "--list":
        print(f"entry: {graph.get('entry')}")
        print(f"states ({len(names)}):")
        for n in names:
            print(f"  {n}")
        return

    if argv[0] == "--meta":
        if len(argv) < 2:
            die(USAGE)
        key = argv[1]
        keys = [k for k in graph if k != "states"]
        if key not in keys:
            die(f"unknown key: {key}\navailable: {', '.join(sorted(keys))}")
        print(json.dumps(graph[key], indent=2))
        return

    name = argv[0]
    if name not in states:
        die(f"unknown state: {name}\navailable:\n  " + "\n  ".join(names))
    print(json.dumps({name: states[name]}, indent=2))


if __name__ == "__main__":
    main(sys.argv[1:])
